version: '3.4'

services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
     MSSQL_SA_PASSWORD: "Passw0rd123"
     ACCEPT_EULA: "Y"
     UserID: "sa"

  mobilitytest:
    image: ${DOCKER_REGISTRY-}mobilitytest
    build:
      context: .
      dockerfile: MobilityTest/Dockerfile

      